In [1]:
import pandas as pd

df = pd.read_csv("amazon_data.csv")

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9336\3520350407.py:3: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("amazon_data.csv")

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [2]:
df.shape

(128975, 24)

In [3]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [5]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.dtypes

index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
Unnamed: 22            object
dtype: object

In [8]:
df.nunique()

index                 128975
Order ID              120378
Date                      91
Status                    13
Fulfilment                 2
Sales Channel              2
ship-service-level         2
Style                   1377
SKU                     7195
Category                   9
Size                      11
ASIN                    7190
Courier Status             3
Qty                       10
currency                   1
Amount                  1410
ship-city               8955
ship-state                69
ship-postal-code        9459
ship-country               1
promotion-ids           5787
B2B                        2
fulfilled-by               1
Unnamed: 22                1
dtype: int64

In [9]:
df['Status'].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [10]:
df.head().T

,0,1,2,3,4
index,0,1,2,3,4
Order ID,405-8078784-5731545,171-9198151-1101146,404-0687676-7273146,403-9615377-8133951,407-1069790-7240320
Date,04-30-22,04-30-22,04-30-22,04-30-22,04-30-22
Status,Cancelled,Shipped - Delivered to Buyer,Shipped,Cancelled,Shipped
Fulfilment,Merchant,Merchant,Amazon,Merchant,Amazon
Sales Channel,Amazon.in,Amazon.in,Amazon.in,Amazon.in,Amazon.in
ship-service-level,Standard,Standard,Expedited,Standard,Expedited
Style,SET389,JNE3781,JNE3371,J0341,JNE3671
SKU,SET389-KR-NP-S,JNE3781-KR-XXXL,JNE3371-KR-XL,J0341-DR-L,JNE3671-TU-XXXL
Category,Set,kurta,kurta,Western Dress,Top
Size,S,3XL,XL,L,3XL
ASIN,B09KXVBD7Z,B09K3WFS32,B07WV4JV4D,B099NRCT7B,B098714BZP
Courier Status,NaN,Shipped,Shipped,NaN,Shipped
Qty,0,1,1,0,1
currency,INR,INR,INR,INR,INR
Amount,647.62,406.0,329.0,753.33,574.0
ship-city,MUMBAI,BENGALURU,NAVI MUMBAI,PUDUCHERRY,CHENNAI
ship-state,MAHARASHTRA,KARNATAKA,MAHARASHTRA,PUDUCHERRY,TAMIL NADU
ship-postal-code,400081.0,560085.0,410210.0,605008.0,600073.0
ship-country,IN,IN,IN,IN,IN
promotion-ids,NaN,Amazon PLCC Free-Financing Universal Merchant ...,IN Core Free Shipping 2015/04/08 23-48-5-108,NaN,NaN
B2B,False,False,True,False,False
fulfilled-by,Easy Ship,Easy Ship,NaN,Easy Ship,NaN
Unnamed: 22,NaN,NaN,NaN,NaN,NaN

In [11]:
df.tail().T

,128970,128971,128972,128973,128974
index,128970,128971,128972,128973,128974
Order ID,406-6001380-7673107,402-9551604-7544318,407-9547469-3152358,402-6184140-0545956,408-7436540-8728312
Date,05-31-22,05-31-22,05-31-22,05-31-22,05-31-22
Status,Shipped,Shipped,Shipped,Shipped,Shipped
Fulfilment,Amazon,Amazon,Amazon,Amazon,Amazon
Sales Channel,Amazon.in,Amazon.in,Amazon.in,Amazon.in,Amazon.in
ship-service-level,Expedited,Expedited,Expedited,Expedited,Expedited
Style,JNE3697,SET401,J0157,J0012,J0003
SKU,JNE3697-KR-XL,SET401-KR-NP-M,J0157-DR-XXL,J0012-SKD-XS,J0003-SET-S
Category,kurta,Set,Western Dress,Set,Set
Size,XL,M,XXL,XS,S
ASIN,B098112V2V,B09VC6KHX8,B0982YZ51B,B0894Y2NJQ,B0894X27FC
Courier Status,Shipped,Shipped,Shipped,Shipped,Shipped
Qty,1,1,1,1,1
currency,INR,INR,INR,INR,INR
Amount,517.0,999.0,690.0,1199.0,696.0
ship-city,HYDERABAD,GURUGRAM,HYDERABAD,Halol,Raipur
ship-state,TELANGANA,HARYANA,TELANGANA,Gujarat,CHHATTISGARH
ship-postal-code,500013.0,122004.0,500049.0,389350.0,492014.0
ship-country,IN,IN,IN,IN,IN
promotion-ids,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,IN Core Free Shipping 2015/04/08 23-48-5-108
B2B,False,False,False,False,False
fulfilled-by,NaN,NaN,NaN,NaN,NaN
Unnamed: 22,False,False,False,False,False

In [12]:
df[['Date', 'Amount', 'Qty', 'currency']].head(10)

       Date  Amount  Qty currency
0  04-30-22  647.62    0      INR
1  04-30-22  406.00    1      INR
2  04-30-22  329.00    1      INR
3  04-30-22  753.33    0      INR
4  04-30-22  574.00    1      INR
5  04-30-22  824.00    1      INR
6  04-30-22  653.00    1      INR
7  04-30-22  399.00    1      INR
8  04-30-22     NaN    0      NaN
9  04-30-22  363.00    1      INR

In [13]:
df[df['Amount'].isna()]['Status'].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [14]:
df[df['Amount'].isna()][['Status', 'Qty', 'currency', 'Category']].head(20)

        Status  Qty currency       Category
8    Cancelled    0      NaN            Set
29   Cancelled    0      NaN          kurta
65   Cancelled    0      NaN          kurta
84   Cancelled    0      NaN          kurta
95   Cancelled    0      NaN          kurta
101  Cancelled    0      NaN            Set
132  Cancelled    0      NaN            Set
139  Cancelled    0      NaN            Top
155  Cancelled    0      NaN          kurta
165  Cancelled    0      NaN          kurta
205  Cancelled    0      NaN            Top
215  Cancelled    0      NaN  Western Dress
242  Cancelled    0      NaN            Top
249  Cancelled    0      NaN          kurta
250  Cancelled    0      NaN          kurta
271  Cancelled    0      NaN            Set
328  Cancelled    0      NaN            Set
363  Cancelled    0      NaN            Set
381  Cancelled    0      NaN            Set
413  Cancelled    0      NaN  Western Dress

In [15]:
df['Date'].nunique(), df['Date'].min(), df['Date'].max()

(91, '03-31-22', '06-29-22')

In [16]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed', errors='coerce')

In [17]:
df['Date'].isna().sum()

np.int64(0)

In [18]:
df[df['Date'].isna()][['Date', 'Status']].head(20)

Empty DataFrame
Columns: [Date, Status]
Index: []

In [19]:
df['Unnamed: 22'].value_counts(dropna=False)

Unnamed: 22
False    79925
NaN      49050
Name: count, dtype: int64

In [20]:
df.drop(columns=['Unnamed: 22'], inplace=True)

In [21]:
df.shape

(128975, 23)

In [22]:
df.isna().sum().sort_values(ascending=False)

fulfilled-by          89698
promotion-ids         49153
Amount                 7795
currency               7795
Courier Status         6872
ship-country             33
ship-postal-code         33
ship-state               33
ship-city                33
B2B                       0
Qty                       0
index                     0
Order ID                  0
Size                      0
Category                  0
SKU                       0
Style                     0
ship-service-level        0
Sales Channel             0
Fulfilment                0
Status                    0
Date                      0
ASIN                      0
dtype: int64

In [23]:
df['fulfilled-by'].value_counts(dropna=False)

fulfilled-by
NaN          89698
Easy Ship    39277
Name: count, dtype: int64

In [24]:
df[df['fulfilled-by'].isna()][['Status', 'Fulfilment', 'Sales Channel', 'fulfilled-by']].head(20)

KeyError: "['Sales Channel'] not in index"

In [25]:
df.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel ',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by']

In [25]:
df.columns = df.columns.str.strip()

In [26]:
df.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by']

In [27]:
df[df['fulfilled-by'].isna()][
    ['Status', 'Fulfilment', 'Sales Channel', 'fulfilled-by']
].head(20)

       Status Fulfilment Sales Channel fulfilled-by
2     Shipped     Amazon     Amazon.in          NaN
4     Shipped     Amazon     Amazon.in          NaN
5     Shipped     Amazon     Amazon.in          NaN
6     Shipped     Amazon     Amazon.in          NaN
8   Cancelled     Amazon     Amazon.in          NaN
9     Shipped     Amazon     Amazon.in          NaN
10    Shipped     Amazon     Amazon.in          NaN
11    Shipped     Amazon     Amazon.in          NaN
13    Shipped     Amazon     Amazon.in          NaN
16    Shipped     Amazon     Amazon.in          NaN
17    Shipped     Amazon     Amazon.in          NaN
19    Shipped     Amazon     Amazon.in          NaN
20    Shipped     Amazon     Amazon.in          NaN
21    Shipped     Amazon     Amazon.in          NaN
22    Shipped     Amazon     Amazon.in          NaN
24    Shipped     Amazon     Amazon.in          NaN
27    Shipped     Amazon     Amazon.in          NaN
28    Shipped     Amazon     Amazon.in          NaN
30    Shipped     Amazon     Amazon.in          NaN
31    Shipped     Amazon     Amazon.in          NaN

In [28]:
df['fulfilled-by'].value_counts(dropna=False)

fulfilled-by
NaN          89698
Easy Ship    39277
Name: count, dtype: int64

In [29]:
pd.crosstab(df['Fulfilment'], df['fulfilled-by'], dropna=False)

fulfilled-by  Easy Ship    NaN
Fulfilment
Amazon                0  89698
Merchant          39277      0

In [30]:
df[['Amount', 'Qty', 'currency']].isna().sum()

Amount      7795
Qty            0
currency    7795
dtype: int64

In [31]:
df[['Amount', 'Qty', 'currency']].head(10)

   Amount  Qty currency
0  647.62    0      INR
1  406.00    1      INR
2  329.00    1      INR
3  753.33    0      INR
4  574.00    1      INR
5  824.00    1      INR
6  653.00    1      INR
7  399.00    1      INR
8     NaN    0      NaN
9  363.00    1      INR

In [32]:
df[['Amount', 'Qty']].describe()

              Amount            Qty
count  121180.000000  128975.000000
mean      648.561465       0.904431
std       281.211687       0.313354
min         0.000000       0.000000
25%       449.000000       1.000000
50%       605.000000       1.000000
75%       788.000000       1.000000
max      5584.000000      15.000000

In [33]:
df[df['Amount'].isna()]['Status'].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [34]:
df[df['Amount'].isna()][['Amount', 'Qty', 'currency', 'Status']].head(20)

     Amount  Qty currency     Status
8       NaN    0      NaN  Cancelled
29      NaN    0      NaN  Cancelled
65      NaN    0      NaN  Cancelled
84      NaN    0      NaN  Cancelled
95      NaN    0      NaN  Cancelled
101     NaN    0      NaN  Cancelled
132     NaN    0      NaN  Cancelled
139     NaN    0      NaN  Cancelled
155     NaN    0      NaN  Cancelled
165     NaN    0      NaN  Cancelled
205     NaN    0      NaN  Cancelled
215     NaN    0      NaN  Cancelled
242     NaN    0      NaN  Cancelled
249     NaN    0      NaN  Cancelled
250     NaN    0      NaN  Cancelled
271     NaN    0      NaN  Cancelled
328     NaN    0      NaN  Cancelled
363     NaN    0      NaN  Cancelled
381     NaN    0      NaN  Cancelled
413     NaN    0      NaN  Cancelled

In [35]:
df[df['Amount'] == 0]['Status'].value_counts()

Status
Shipped                          1518
Shipped - Delivered to Buyer      716
Shipped - Returned to Seller       51
Shipped - Picked Up                28
Pending                            17
Pending - Waiting for Pick Up       9
Shipped - Lost in Transit           2
Shipped - Returning to Seller       2
Name: count, dtype: int64

In [36]:
df[df['Amount'] == 0][['Amount', 'Qty', 'currency', 'Status']].head(20)

      Amount  Qty currency                        Status
212      0.0    1      INR  Shipped - Delivered to Buyer
374      0.0    1      INR  Shipped - Returned to Seller
385      0.0    1      INR                       Shipped
388      0.0    1      INR  Shipped - Delivered to Buyer
392      0.0    1      INR                       Shipped
436      0.0    1      INR                       Shipped
441      0.0    1      INR  Shipped - Delivered to Buyer
446      0.0    1      INR                       Shipped
449      0.0    1      INR                       Shipped
729      0.0    1      INR  Shipped - Delivered to Buyer
731      0.0    1      INR  Shipped - Returned to Seller
827      0.0    1      INR                       Shipped
844      0.0    1      INR                       Shipped
930      0.0    1      INR                       Shipped
947      0.0    1      INR  Shipped - Delivered to Buyer
986      0.0    1      INR  Shipped - Delivered to Buyer
1071     0.0    1      INR                       Shipped
1104     0.0    1      INR  Shipped - Delivered to Buyer
1115     0.0    1      INR                       Shipped
1226     0.0    1      INR  Shipped - Delivered to Buyer

In [37]:
df[df['Amount'] == 0][['Qty', 'currency']].value_counts(dropna=False)

Qty  currency
1    INR         2343
Name: count, dtype: int64

In [38]:
df[df['Amount'] == 0]['Status'].value_counts()

Status
Shipped                          1518
Shipped - Delivered to Buyer      716
Shipped - Returned to Seller       51
Shipped - Picked Up                28
Pending                            17
Pending - Waiting for Pick Up       9
Shipped - Lost in Transit           2
Shipped - Returning to Seller       2
Name: count, dtype: int64

In [39]:
df[df['Amount'] == 0]['Category'].value_counts()

Category
Set              1013
kurta             858
Western Dress     231
Top               174
Ethnic Dress       32
Blouse             22
Bottom             12
Saree               1
Name: count, dtype: int64

In [40]:
df[df['Amount'] == 0]['Fulfilment'].value_counts()

Fulfilment
Amazon      1527
Merchant     816
Name: count, dtype: int64

In [41]:
df[df['Amount'] > 0]['Status'].value_counts()

Status
Shipped                          76078
Shipped - Delivered to Buyer     28045
Cancelled                        10766
Shipped - Returned to Seller      1899
Shipped - Picked Up                945
Pending                            639
Pending - Waiting for Pick Up      272
Shipped - Returning to Seller      143
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipped - Lost in Transit            3
Shipped - Damaged                    1
Name: count, dtype: int64

In [42]:
df['Amount'].sum()

np.float64(78592678.29999998)

In [43]:
df['Order ID'].nunique()

120378

In [44]:
df['Qty'].sum()

np.int64(116649)

In [45]:
df.groupby(df['Date'].dt.to_period('M'))['Amount'].sum()

Date
2022-03      101683.85
2022-04    28838708.32
2022-05    26226476.75
2022-06    23425809.38
Freq: M, Name: Amount, dtype: float64

In [46]:
df.groupby(df['Date'].dt.to_period('M'))['Order ID'].nunique()

Date
2022-03      158
2022-04    45858
2022-05    39221
2022-06    35141
Freq: M, Name: Order ID, dtype: int64

In [47]:
df.groupby('Category')['Amount'].sum().sort_values(ascending=False)

Category
Set              39204124.03
kurta            21299546.70
Western Dress    11216072.69
Top               5347792.30
Ethnic Dress       791217.66
Blouse             458408.18
Bottom             150667.98
Saree              123933.76
Dupatta               915.00
Name: Amount, dtype: float64

In [48]:
df.groupby('Category')['Qty'].sum().sort_values(ascending=False)

Category
Set              45289
kurta            45045
Western Dress    13943
Top               9903
Ethnic Dress      1053
Blouse             863
Bottom             398
Saree              152
Dupatta              3
Name: Qty, dtype: int64

In [49]:
df.groupby('Category').agg(
    Total_Sales=('Amount', 'sum'),
    Total_Qty=('Qty', 'sum')
).assign(
    Avg_Amount_Per_Unit=lambda x: x['Total_Sales'] / x['Total_Qty']
).sort_values('Avg_Amount_Per_Unit', ascending=False)

               Total_Sales  Total_Qty  Avg_Amount_Per_Unit
Category
Set            39204124.03      45289           865.643402
Saree            123933.76        152           815.353684
Western Dress  11216072.69      13943           804.423201
Ethnic Dress     791217.66       1053           751.393789
Top             5347792.30       9903           540.017399
Blouse           458408.18        863           531.179815
kurta          21299546.70      45045           472.850410
Bottom           150667.98        398           378.562764
Dupatta             915.00          3           305.000000

In [50]:
status_pct = df['Status'].value_counts(normalize=True) * 100
status_pct.round(2)

Status
Shipped                          60.32
Shipped - Delivered to Buyer     22.31
Cancelled                        14.21
Shipped - Returned to Seller      1.51
Shipped - Picked Up               0.75
Pending                           0.51
Pending - Waiting for Pick Up     0.22
Shipped - Returning to Seller     0.11
Shipped - Out for Delivery        0.03
Shipped - Rejected by Buyer       0.01
Shipping                          0.01
Shipped - Lost in Transit         0.00
Shipped - Damaged                 0.00
Name: proportion, dtype: float64

In [51]:
df[df['Status'] == 'Cancelled']['Category'].value_counts()

Category
Set              7337
kurta            7255
Western Dress    2122
Top              1276
Ethnic Dress      145
Blouse            116
Bottom             60
Saree              21
Name: count, dtype: int64

In [52]:
cancel_rate = (
    df.groupby('Category')['Status']
      .apply(lambda x: (x == 'Cancelled').mean() * 100)
      .sort_values(ascending=False)
)

cancel_rate.round(2)

Category
Set              14.59
kurta            14.55
Western Dress    13.69
Bottom           13.64
Saree            12.80
Blouse           12.53
Ethnic Dress     12.51
Top              12.01
Dupatta           0.00
Name: Status, dtype: float64

In [53]:
df.groupby('ship-state')['Amount'].sum().sort_values(ascending=False).head(10)

ship-state
MAHARASHTRA       13335534.14
KARNATAKA         10481114.37
TELANGANA          6916615.65
UTTAR PRADESH      6816642.08
TAMIL NADU         6515650.11
DELHI              4235215.97
KERALA             3830227.58
WEST BENGAL        3507880.44
ANDHRA PRADESH     3219831.72
HARYANA            2882092.99
Name: Amount, dtype: float64

In [54]:
df.groupby('ship-state')['Order ID'].nunique().sort_values(ascending=False).head(10)

ship-state
MAHARASHTRA       20780
KARNATAKA         16182
TAMIL NADU        10519
TELANGANA         10405
UTTAR PRADESH     10062
DELHI              6359
KERALA             6105
WEST BENGAL        5653
ANDHRA PRADESH     4979
Gujarat            4169
Name: Order ID, dtype: int64

In [55]:
state_analysis = df.groupby('ship-state').agg(
    Total_Sales=('Amount', 'sum'),
    Unique_Orders=('Order ID', 'nunique')
)

state_analysis['Avg_Order_Value'] = (
    state_analysis['Total_Sales'] / state_analysis['Unique_Orders']
)

state_analysis.sort_values(
    'Avg_Order_Value',
    ascending=False
).head(10)

             Total_Sales  Unique_Orders  Avg_Order_Value
ship-state
bihar            1432.00              1      1432.000000
delhi           16553.62             17       973.742353
LADAKH          38388.43             42       914.010238
Sikkim           2703.00              3       901.000000
NAGALAND       143430.67            167       858.866287
Chandigarh       9054.62             11       823.147273
LAKSHADWEEP      3175.29              4       793.822500
rajasthan        3946.00              5       789.200000
Rajasthan       37252.76             49       760.260408
MANIPUR        211350.99            282       749.471596

In [56]:
state_analysis[state_analysis['Unique_Orders'] >= 500] \
    .sort_values('Avg_Order_Value', ascending=False) \
    .head(10)

                  Total_Sales  Unique_Orders  Avg_Order_Value
ship-state
BIHAR              1394388.32           1989       701.049935
RAJASTHAN          1716802.40           2452       700.164111
HARYANA            2882092.99           4142       695.821581
ODISHA             1372205.63           2000       686.102815
JAMMU & KASHMIR     456932.74            670       681.989164
UTTAR PRADESH      6816642.08          10062       677.463932
HIMACHAL PRADESH    503364.51            750       671.152680
MADHYA PRADESH     1592382.98           2375       670.477044
PUNJAB             1180064.84           1762       669.730329
DELHI              4235215.97           6359       666.019181

In [57]:
top_states = (
    df.groupby('ship-state')
      .agg(
          Total_Sales=('Amount', 'sum'),
          Unique_Orders=('Order ID', 'nunique')
      )
      .sort_values('Total_Sales', ascending=False)
      .head(10)
)
top_states

                Total_Sales  Unique_Orders
ship-state
MAHARASHTRA     13335534.14          20780
KARNATAKA       10481114.37          16182
TELANGANA        6916615.65          10405
UTTAR PRADESH    6816642.08          10062
TAMIL NADU       6515650.11          10519
DELHI            4235215.97           6359
KERALA           3830227.58           6105
WEST BENGAL      3507880.44           5653
ANDHRA PRADESH   3219831.72           4979
HARYANA          2882092.99           4142

In [58]:
fulfilment_sales = (
    df.groupby('Fulfilment')['Amount']
      .sum()
      .sort_values(ascending=False)
)

fulfilment_sales

Fulfilment
Amazon      54322151.0
Merchant    24270527.3
Name: Amount, dtype: float64

In [59]:
fulfilment_analysis = (
    df.groupby('Fulfilment')
      .agg(
          Total_Sales=('Amount', 'sum'),
          Unique_Orders=('Order ID', 'nunique')
      )
)

fulfilment_analysis['Avg_Order_Value'] = (
    fulfilment_analysis['Total_Sales'] /
    fulfilment_analysis['Unique_Orders']
)

fulfilment_analysis

            Total_Sales  Unique_Orders  Avg_Order_Value
Fulfilment
Amazon       54322151.0          84002       646.676877
Merchant     24270527.3          36376       667.212648

In [60]:
df['Sales Channel'].value_counts()

Sales Channel
Amazon.in     128851
Non-Amazon       124
Name: count, dtype: int64

In [61]:
df.groupby(['Sales Channel', 'Fulfilment']).size()

Sales Channel  Fulfilment
Amazon.in      Amazon        89574
               Merchant      39277
Non-Amazon     Amazon          124
dtype: int64

In [62]:
df['Courier Status'].value_counts(dropna=False)

Courier Status
Shipped      109487
NaN            6872
Unshipped      6681
Cancelled      5935
Name: count, dtype: int64

In [63]:
df[df['Courier Status'].isna()]['Status'].value_counts()

Status
Cancelled                       6861
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [64]:
pd.crosstab(
    df['Status'],
    df['Courier Status'],
    dropna=False
)

Courier Status                 Cancelled  Shipped  Unshipped   NaN
Status
Cancelled                           5840        0       5631  6861
Pending                                2       10        646     0
Pending - Waiting for Pick Up          0        0        281     0
Shipped                               93    77596        115     0
Shipped - Damaged                      0        1          0     0
Shipped - Delivered to Buyer           0    28761          0     8
Shipped - Lost in Transit              0        5          0     0
Shipped - Out for Delivery             0       35          0     0
Shipped - Picked Up                    0      973          0     0
Shipped - Rejected by Buyer            0       11          0     0
Shipped - Returned to Seller           0     1950          0     3
Shipped - Returning to Seller          0      145          0     0
Shipping                               0        0          8     0